### ISSUE TITLE
Error: Cannot find module 'mongodb/node_modules/bson'

### ISSUE THREAD

**Issue by KingScooty** [mjhea0/node-stripe-charge#7]
Seem to be getting this issue when starting the server:

```sh
> node ./server/bin/www

module.js:328
    throw err;
    ^

Error: Cannot find module 'mongodb/node_modules/bson'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/KingScooty/Sites/Playground/node-stripe-charge/node_modules/mongoose/lib/drivers/node-mongodb-native/objectid.js:8:16)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.4.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! node-stripe-charge@1.0.0 start: `node ./server/bin/www`
npm ERR! Exit status 1
```

**Comment by mjhea0** [comment]
I updated the dependencies. Clone down the latest version. Cheers!
