### ISSUE TITLE
Consistently getting an error (also had trouble with NPM install)

### ISSUE THREAD

**Issue by dstroot** [mjhea0/node-stripe-charge#9]
Everything appears to be working - I can create accounts and login and the products are listed.  I updated the .env file with my Stripe test keys.  However when I try to make a charge I keep getting this error:

**No such token: tok_83IqDvlTYkipyY**

```
Error: No such token: tok_83IqDvlTYkipyY
    at Error._Error (/Users/Dan/Code/node-stripe-charge/node_modules/stripe/lib/Error.js:12:17)
    at Error.Constructor (/Users/Dan/Code/node-stripe-charge/node_modules/stripe/lib/utils.js:105:13)
    at Error.Constructor (/Users/Dan/Code/node-stripe-charge/node_modules/stripe/lib/utils.js:105:13)
    at Function.StripeError.generate (/Users/Dan/Code/node-stripe-charge/node_modules/stripe/lib/Error.js:56:14)
    at IncomingMessage.<anonymous> (/Users/Dan/Code/node-stripe-charge/node_modules/stripe/lib/StripeResource.js:138:39)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)
```

Help!  Thanks!  

- Dan

**Comment by mjhea0** [comment]
Hi @dstroot - That error has to do with your Stripe keys. Can't really help much there. Check out this article -> http://stackoverflow.com/questions/33137053/no-such-token-error-upon-submitting-payment-request-to-stripe. Best!

**Comment by dstroot** [comment]
I am using the exact same keys in another app.  Odd....  Double checked them too.

**Comment by mjhea0** [comment]
Is this the publishable key?

**Comment by dstroot** [comment]
No need to reopen - will check everything out tomorrow and if I can't get it working I will re-comment

**Comment by matthewarkin** [comment]
This is caused because the key is hard coded at https://github.com/mjhea0/node-stripe-charge/blob/master/src/client/js/main.js#L1 and not actually read from the .env file
